In [1]:
import numpy as np

print(np.__version__)

2.2.4


In [2]:
arr = np.array(10)

arr2 = np.array([1,3,4,2,9])

lst = [12, 90, 30, -2]

arr3 = np.array(lst)

arr4 = np.array([['haha', 'meow'], ['pew', 'hehe']])

print(arr4)

print(type(arr))
print(arr4.ndim)
print(arr4.shape)

[['haha' 'meow']
 ['pew' 'hehe']]
<class 'numpy.ndarray'>
2
(2, 2)


In [3]:
arr5 = np.array([['haha', 'meow'], ['pew', 'hehe']], ndmin = 4)

print(arr5.ndim)
print(arr5.shape)

4
(1, 1, 2, 2)


In [11]:
print(arr5)

print(arr5[0][0])

print(arr5[0][0][0])
print(arr5[0][0][1])

print(arr5[0][0][0][0])

print(arr5[0,0,1,1])

[[[['haha' 'meow']
   ['pew' 'hehe']]]]
[['haha' 'meow']
 ['pew' 'hehe']]
['haha' 'meow']
['pew' 'hehe']
haha
hehe


**This part from puran yt**

In [12]:
a = np.array(4.)
print(a)

4.0


In [14]:
a = np.arange(4.)
print(a)
print(a.shape)
print(a.dtype)

[0. 1. 2. 3.]
(4,)
float64


In [15]:
a = np.zeros((4,))
print(a)

[0. 0. 0. 0.]


In [16]:
a = np.random.rand(4)
print(a)

[0.60180887 0.31540598 0.43623136 0.13011081]


In [17]:
a = np.arange(4)
b = -a
print(b)

s = np.sum(a)
print(s)

print(a**3)
print(a+b)

[ 0 -1 -2 -3]
6
[ 0  1  8 27]
[0 0 0 0]


In [18]:
d = np.array([1,10])

try:
    s=a+d
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (4,) (2,) 


In [19]:
def dotproduct(a,b):
    #parameters are two arrays of same dimension
    
    x = 0
    for i in range(a.shape[0]):
        x = x+a[i]*b[i]
    return x


a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 2, 2])

print(f"dot(a,b) = {dotproduct(a, b)}")

dot(a,b) = 20


In [20]:
r = np.dot(a, b)
print(f"dot(a,b) by numpy = {r} and shape = {r.shape}")

dot(a,b) by numpy = 20 and shape = ()


**Numpy Matrix**

past yt vid theke

In [21]:
a = np.zeros((2,5))

print(a)
print(a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)


In [22]:
a = np.random.random_sample((4,3))
print(a)
print(a.shape)

[[0.56799384 0.37088225 0.49288637]
 [0.22111355 0.58103003 0.88877254]
 [0.50194035 0.0251174  0.59440431]
 [0.75425157 0.74695762 0.91029411]]
(4, 3)


In [23]:
a = np.array([[2,3], [4,5], [6,7]])

print(a)
print(a.shape)

[[2 3]
 [4 5]
 [6 7]]
(3, 2)


In [26]:
a = np.arange(6).reshape(-1, 2)

#2 = no of columns, -1 tells the computer to do the math, instead of writing 3,2
print(a)
print(a.shape)

print(f"row 2 = {a[2]} and type = {type(a[2])}")

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
row 2 = [4 5] and type = <class 'numpy.ndarray'>


In [27]:
a = np.arange(20).reshape(-1, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [31]:
#prothom parameter ta hocche original matrix er row ta, : thakle all rows

print(f"a[0, 3:11:2] = {a[0, 3:11:2]} and shape = {a[0, 3:11:2].shape}")

print(f"a[0, 3:11:1] = {a[0, 3:11:1]} and shape = {a[0, 3:11:1].shape}")
print(f"a[0, 2:5:2] = {a[0, 2:5:2]} and shape = {a[0, 2:5:2].shape}")

print(f"a[:, 3:11:2] = {a[:, 3:11:2]} and shape = {a[:, 3:11:2].shape}")


a[0, 3:11:2] = [3] and shape = (1,)
a[0, 3:11:1] = [3 4] and shape = (2,)
a[0, 2:5:2] = [2 4] and shape = (2,)
a[:, 3:11:2] = [[ 3]
 [ 8]
 [13]
 [18]] and shape = (4, 1)


In [35]:
print(f"a[:, :] = {a[:, :]} and shape = {a[:, :].shape}")

print(f"\na[1, :] = {a[1, :]} and shape = {a[1, :].shape}")

print(f"a[1, ::-2] = {a[1, ::-2]} and shape = {a[1, ::-2].shape}")


a[:, :] = [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] and shape = (4, 5)

a[1, :] = [5 6 7 8 9] and shape = (5,)
a[1, ::-2] = [9 7 5] and shape = (3,)


**Back to class**

In [41]:
a = np.arange(6).reshape(-1,2)
b = a.view()
c = a.copy()

#changing a will change b too
a[1][1] = 13
print(b)
print(c)

b[1][0] = -9
print(b)

print(f"base of b = {b.base}")

[[ 0  1]
 [ 2 13]
 [ 4  5]]
[[0 1]
 [2 3]
 [4 5]]
[[ 0  1]
 [-9 13]
 [ 4  5]]
base of b = [ 0  1 -9 13  4  5]


In [42]:
a = np.ones(10)
print(a)

b = np.empty(5)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.00000000e+000 6.95319128e-310 4.94065646e-324             nan
 0.00000000e+000]


In [43]:
a = np.arange(6)

b = np.transpose(a)
c = a.T

print(a)
print(b)
print(c)
print(c.transpose())

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [47]:
print(np.concatenate((a,b)))
print(np.vstack((a,b)))

[0 1 2 3 4 5 0 1 2 3 4 5]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [50]:
a = [2, 4, -1, 0]
print(np.sort(a))

[-1  0  2  4]
